ACCEPT EMP_ID PROMPT 'ENTER A VALID EMPLOYEE ID';
SELECT first_name, last_name,EMPLOYEE_ID FROM employees WHERE EMPLOYEE_ID = &EMP_ID;


ACCEPT MIN_SAL PROMPT 'PLEASE ENTER THE MINIMUM SALARY'
ACCEPT MAX_SAL PROMPT 'PLEASE ENTER THE MAXIMUM SALARY'
SELECT FIRST_NAME,LAST_NAME,SALARY FROM EMPLOYEES
WHERE SALARY BETWEEN &MIN_SAL AND &MAX_SAL;

UNDEF MIN_SAL
UNDEF MAX_SAL



SET VERIFY OFF;
ACCEPT MIN_SAL PROMPT 'PLEASE ENTER THE MINIMUM SALARY'
ACCEPT MAX_SAL PROMPT 'PLEASE ENTER THE MAXIMUM SALARY'
SELECT FIRST_NAME,LAST_NAME,SALARY FROM EMPLOYEES
WHERE SALARY BETWEEN &MIN_SAL AND &MAX_SAL;



SET VERIFY ON;
SET VERIFY OFF;
SET DEFINE ON;
SET DEFINE OFF;
