--AND OPERATOR
--EMPLOYEES HAVING JOB_ID AS SA_REP AND GETTING SALARY MORE THAN 10000
SELECT * FROM EMPLOYEES WHERE JOB_ID = 'SA_REP' 
                          AND SALARY > 10000;

--OR OPERATOR
--EMPLOYEES HAVING FIRST NAME AS LISA OR ELLEN
SELECT * FROM EMPLOYEES WHERE FIRST_NAME = 'Lisa' 
                         OR FIRST_NAME = 'Ellen';
                         
--NOT OPERATOR 
--ALL EMPLOYEES EXCEPT EMPLOYEES FROM DEPARTMENT_ID - 80,100
SELECT * FROM EMPLOYEES 
WHERE DEPARTMENT_ID NOT IN(80,100);