--OPERATION ON COLUMN VALUE : NUMBER DATA TYPE
SELECT employee_id,salarY,salary*12 AS ANNUAL_SALARY FROM employees;

--OPERATION ON COLUMN VALUE : DATE DATA TYPE

SELECT SYSDATE FROM DUAL;

SELECT SYSDATE+4 FROM DUAL;

SELECT hire_date FROM EMPLOYEES;

SELECT hire_date+4 FROM EMPLOYEES;

--NULL*VALUES RETURNS NULL VALUE //IMP

SELECT SALARY,commission_pct,commission_pct*salary FROM EMPLOYEES ;