--CHARECTER FUNCTIONS :

--CASE CONVERSION FUNCTIONS : UPPER , LOWER , INITCAP
SELECT UPPER(FIRST_NAME),LOWER(LAST_NAME),INITCAP(JOB_ID) FROM EMPLOYEES;

--NOT RECOMMENDED MORE COSTLY
SELECT * FROM EMPLOYEES
WHERE UPPER(LAST_NAME) = 'KING';