--CHARECTER MANIPULATION FUNCTIONS

--SUBSTR RETURNS CHARECTERS FROM SPECIFIC START TO N CHARECTERS
SELECT FIRST_NAME, SUBSTR(FIRST_NAME,1,4) FROM EMPLOYEES;
SELECT LAST_NAME, SUBSTR(LAST_NAME,2,5) FROM EMPLOYEES;


--LENGTH USED TO CALCULATE THE LENGTH 
    SELECT FIRST_NAME,LAST_NAME,LENGTH(FIRST_NAME),LENGTH(LAST_NAME) FROM EMPLOYEES;


--CONCATENATTION : JOINS TWO COLUMNS
    SELECT CONCAT(FIRST_NAME,LAST_NAME) FROM EMPLOYEES;


--INSTR : Find the position of the substring from the column . 
    --search for small o from beggining
    SELECT INSTR('Hello,I am learning oracle in udemy','o') from dual;

    --search for small o after position 6 
    SELECT INSTR('Hello,I am learning oracle in udemy','o',6) from dual;

    --search for small o from the end to beggining
    SELECT INSTR('Hello,I am learning oracle in udemy','o',-1,1) from dual;
    
    
    
--TRIM  : Remove spaces or charecters from the value specified.

--REMOVES BOTH SIDE SPACES
    SELECT TRIM('   MY NAME IS VENKATESH    ') AS TRIM_TEXT FROM DUAL;

--REMOVES BOTH SIDE SPACES
    SELECT TRIM(BOTH ' ' FROM '   MY NAME IS VENKATESH    ')  AS TRIM_TEXT FROM DUAL;

--REMOVES SPACES IN THE BEGGINING 
    SELECT TRIM(LEADING ' ' FROM '   MY NAME IS VENKATESH    ')  AS TRIM_TEXT FROM DUAL;

--REMOVES SPACES AT THE ENDING
    SELECT TRIM(TRAILING ' ' FROM '   MY NAME IS VENKATESH    ')  AS TRIM_TEXT FROM DUAL;


--lly WE CAN ALSO DELTE CHARECTER

    SELECT TRIM(LEADING 'M' FROM 'MY NAME IS VENKATESH')  AS TRIM_TEXT FROM DUAL;
    
    
    
--RTRIM : REMOVES CHARECTERS OR SPACES ON THE RIGHT SIDE 
    SELECT RTRIM(' MY NAME IS VENKATESH    ') AS TRIM_TEXT FROM DUAL;
    
    SELECT RTRIM('MY NAME IS VENKATESH' , 'H') AS TRIM_TEXT FROM DUAL;
    
    
--LTRIM : REMOVES CHARECTERS OR SPACES ON THE LEFT SIDE 
    SELECT LTRIM(' MY NAME IS VENKATESH    ') AS TRIM_TEXT FROM DUAL;
    
    SELECT LTRIM('MY NAME IS VENKATESH', 'M') AS TRIM_TEXT FROM DUAL;
    
   SELECT RTRIM(LTRIM('WWW.MYWEBSITE.COM','W.'),'.COM') AS TRIM_TEXT FROM DUAL;
   
   



--REPLACE : TO REPLACE A STRING WITH ANOTHER 
    --REPLACE A CHARECTE a WITH b.
    SELECT FIRST_NAME , REPLACE(FIRST_NAME,'a','b') REPLACE_FIRSTNAME FROM EMPLOYEES;
    
    
--lpad : fill the string with additional necessary charecters IN THE BEGGINING
     -- add * UNTILL THE STRING LENGTH BECOMES 10.
     SELECT FIRST_NAME , LPAD(FIRST_NAME,10,'*') LPAD_STRING FROM EMPLOYEES;
     SELECT FIRST_NAME , LPAD(FIRST_NAME,20,'*') LPAD_STRING FROM EMPLOYEES;
     
--lpad : fill the string with additional necessary charecters IN THE ENDING
     -- add * UNTILL THE STRING LENGTH BECOMES 10.
     SELECT FIRST_NAME , RPAD(FIRST_NAME,10,'*') LPAD_STRING FROM EMPLOYEES;
     SELECT FIRST_NAME , RPAD(FIRST_NAME,20,'*') LPAD_STRING FROM EMPLOYEES;
     SELECT FIRST_NAME, LPAD('MY NAME IS'||LAST_NAME,20, '=') PAD_STRING FROM EMPLOYEES;
    
    