--CONDITIONAL EXPRESSIONS


--CASE EXPRESSION IN SELECT CLAUSE
SELECT FIRST_NAME,LAST_NAME,JOB_ID,SALARY,HIRE_DATE,
    CASE JOB_ID WHEN 'ST_MAN' THEN 1.20 * SALARY
                WHEN 'SH_MAN' THEN 1.30 * SALARY
                WHEN 'SA_MAN' THEN 1.40 * SALARY
                ELSE SALARY END "UPDATED_SALARY"
    FROM EMPLOYEES;
    
    
--CASE EXPRESSION IN WHERE CLAUSE 

SELECT FIRST_NAME,LAST_NAME,JOB_ID,SALARY
FROM EMPLOYEES
WHERE 
    (CASE 
     WHEN JOB_ID = 'ST_MAN' AND SALARY > 5000 THEN 1
     WHEN JOB_ID = 'SA_MAN' AND SALARY > 10000 THEN 1
     ELSE 0
     END) = 1 ;
     
     
     
--DECODE FUNCTION

SELECT FIRST_NAME,LAST_NAME,JOB_ID,SALARY,HIRE_DATE,
       DECODE(JOB_ID,'ST_MAN',SALARY*1.20,
                     'SH_MAN',SALARY*1.30,
                     'SA_MAN',SALARY*1.40,
                     SALARY) AS UPDATED_SALARY
       FROM EMPLOYEES WHERE JOB_ID IN ('ST_MAN','SH_MAN','SA_MAN');
       
       
    
SELECT DECODE(1,1,'ONE',2,'TWO') RESULT FROM DUAL;
SELECT DECODE(2,1,'ONE',2,'TWO') RESULT FROM DUAL;
SELECT DECODE(3,1,'ONE',2,'TWO','NOT FOUND') RESULT FROM DUAL;