-- ADD MONTHS TO A DATE 
SELECT SYSDATE,ADD_MONTHS(SYSDATE,5) FROM DUAL;
SELECT HIRE_DATE,ADD_MONTHS(HIRE_DATE,6) AS END_OF_NOTICE_PERIOD FROM EMPLOYEES;

--MONTHS BETWEEN SPECIFIED DATES 
SELECT TRIM(TRUNC(MONTHS_BETWEEN(SYSDATE,hire_date))) AS MONTHS_WORKED FROM EMPLOYEES;

--ROUND
SELECT ROUND(SYSDATE,'MONTH') FROM DUAL;


--TRUNC
SELECT EMPLOYEE_ID,HIRE_DATE, 
       TRUNC(HIRE_DATE,'MONTH') AS TRUNCATED_RESULT ,
       ROUND(HIRE_DATE,'MONTH') AS ROUNDED_DATE
FROM EMPLOYEES;


--EXTRACT

SELECT EXTRACT(MONTH FROM SYSDATE) FROM DUAL;
SELECT EXTRACT(YEAR FROM SYSDATE) FROM DUAL;
SELECT EXTRACT(DAY FROM SYSDATE) FROM DUAL;


--  NEXT DAY

SELECT NEXT_DAY('01-07-21','WEDNESDAY') FROM DUAL;
SELECT NEXT_DAY(SYSDATE,'SATURDAY') FROM DUAL;

--LAST_DAY
SELECT LAST_DAY('04-07-21') FROM DUAL;