--AVG FUNCTION
SELECT AVG(SALARY),AVG(ALL SALARY),AVG(DISTINCT SALARY) FROM EMPLOYEES;


SELECT AVG(SALARY),AVG(ALL SALARY),AVG(DISTINCT SALARY) FROM EMPLOYEES
WHERE JOB_ID = 'IT_PROG';


SELECT AVG(COMMISSION_PCT),AVG(NVL(COMMISSION_PCT,0)) FROM EMPLOYEES;



--COUNT FUNCTION

SELECT COUNT(*), COUNT(MANAGER_ID), COUNT(ALL MANAGER_ID),
COUNT(DISTINCT MANAGER_ID) FROM EMPLOYEES;




SELECT COUNT(*),COUNT(ALL COMMISSION_PCT),
       COUNT(DISTINCT COMMISSION_PCT),
       COUNT(NVL(COMMISSION_PCT,0)),
       COUNT(DISTINCT NVL(COMMISSION_PCT,0))
       FROM EMPLOYEES;
       
       
       
--Max Function 
SELECT MAX(SALARY) FROM EMPLOYEES;

--LATEST HIRE DATA
SELECT MAX(HIRE_DATE) FROM EMPLOYEES;


--MIN FUCNTION

SELECT MIN(SALARY),MIN(COMMISSION_PCT),MIN(NVL(COMMISSION_PCT,0)),MIN(HIRE_DATE),MIN(FIRST_NAME) FROM EMPLOYEES;




--SUM FUNCTION

SELECT SUM(SALARY),SUM(ALL SALARY),SUM(DISTINCT SALARY) FROM EMPLOYEES;




--LISTAGG FUNCTION
SELECT LISTAGG(FIRST_NAME,',') WITHIN GROUP (ORDER BY FIRST_NAME DESC) AS EMPLOYEES
FROM EMPLOYEES
WHERE JOB_ID = 'ST_CLERK

SELECT LISTAGG(FIRST_NAME,',') WITHIN GROUP (ORDER BY LAST_NAME DESC) AS EMPLOYEES
FROM EMPLOYEES
WHERE JOB_ID = 'ST_CLERK';



SELECT LISTAGG(DISTINCT SALARY,',') WITHIN GROUP (ORDER BY SALARY DESC) AS EMPLOYEES
FROM EMPLOYEES
WHERE JOB_ID = 'ST_CLERK';


SELECT * FROM LOCATIONS;

SELECT LISTAGG(CITY,',') WITHIN GROUP (ORDER BY CITY) FROM LOCATIONS
WHERE COUNTRY_ID='UK';


--REAL WORLD IMPLIMENTATION OF LISTAGG

SELECT J.JOB_TITLE, LISTAGG(E.FIRST_NAME,', ') WITHIN GROUP (ORDER BY E.FIRST_NAME) AS EMPLOYEE_LIST 
FROM EMPLOYEES E,JOBS J
WHERE E.JOB_ID = J.JOB_ID
GROUP BY J.JOB_TITLE;


