--Implicit DATA type conversion

--CONVERSION FROM VARCHAR2 TO NUMBER
SELECT * FROM EMPLOYEES WHERE SALARY > '5000';


--CONVERSTION FROM VARCHAR2 TO DATE VALUE
SELECT * FROM EMPLOYEES WHERE HIRE_DATE='17-JUN-03';


--CONVERSTION FROM NUMBER TO VARCHAR2 
SELECT DEPARTMENT_ID || DEPARTMENT_NAME FROM DEPARTMENTS;