SELECT FIRST_NAME , LAST_NAME , LPAD(UPPER(CONCAT(FIRST_NAME, LAST_NAME)),20,'*') AS NESTED_FUNCTION FROM EMPLOYEES;


SELECT SUBSTR('JOHN SMITH',instr('JOHN SMITH',' ')+1,LENGTH('JOHN SMITH')) AS OUTPUT FROM DUAL;


SELECT FIRST_NAME|| ' ' ||LAST_NAME AS FULL_NAME,
       SUBSTR(FIRST_NAME|| ' ' ||LAST_NAME,
       instr(FIRST_NAME|| ' ' ||LAST_NAME,' ')+1) AS OUTPUT FROM EMPLOYEES;