--NULLS FIRST , NULLS LAST 


--employees salary more than 9000 showing the null commissions first ;
SELECT FIRST_NAME,LAST_NAME,SALARY,COMMISSION_PCT AS COMMISSION FROM EMPLOYEES 
WHERE SALARY >9000 ORDER BY COMMISSION NULLS FIRST;


--employees salary more than 9000 showing the null commissions last ;
SELECT FIRST_NAME,LAST_NAME,SALARY,COMMISSION_PCT AS COMMISSION FROM EMPLOYEES 
WHERE SALARY >9000 ORDER BY COMMISSION NULLS LAST;


--employees salary more than 9000 sorted by salary and null commissions ;
SELECT FIRST_NAME,LAST_NAME,SALARY,COMMISSION_PCT AS COMMISSION FROM EMPLOYEES 
WHERE SALARY >9000 ORDER BY SALARY DESC NULLS LAST,COMMISSION NULLS FIRST;