--NVL FUNCTION 

SELECT JOB_ID,FIRST_NAME,LAST_NAME,COMMISSION_PCT,
        NVL(COMMISSION_PCT,0) AS NVL_COMM_PCT FROM EMPLOYEES
        WHERE JOB_ID IN('SA_REP','IT_PROG');
        

SELECT EMPLOYEE_ID,SALARY,COMMISSION_PCT,SALARY+SALARY*NVL(COMMISSION_PCT,0) NEW_SAL FROM EMPLOYEES;


--NVL2 FUNCTION
SELECT JOB_ID,FIRST_NAME,LAST_NAME,COMMISSION_PCT,
        NVL2(COMMISSION_PCT,'HAS','DOESNT HAS') AS NVL_COMM_PCT_STATUS FROM EMPLOYEES
        WHERE JOB_ID IN('SA_REP','IT_PROG');
        
        
--NULLIF FUNCTION
SELECT FIRST_NAME,LAST_NAME,LENGTH(FIRST_NAME) AS LEN1,LENGTH(LAST_NAME) AS LEN2 ,
        NULLIF(LENGTH(FIRST_NAME),LENGTH(LAST_NAME)) AS RESULT FROM EMPLOYEES;
        

SELECT FIRST_NAME,LAST_NAME,LENGTH(FIRST_NAME) AS LEN1,LENGTH(LAST_NAME) AS LEN2 ,
        NULLIF(LENGTH(FIRST_NAME),LENGTH(LAST_NAME)) AS RESULT FROM EMPLOYEES
        WHERE NULLIF(LENGTH(FIRST_NAME),LENGTH(LAST_NAME)) IS NULL;      
        
    
    
--coalesce function
SELECT COALESCE(NULL,NULL,5,4,3,2,1) FROM DUAL;


SELECT STATE_PROVINCE,CITY,COALESCE(STATE_PROVINCE,CITY) FROM LOCATIONS;

SELECT coalesce(NULLIF(4500.00,4500),1) FROM DUAL;