-OPERATOR PRECENDENCE 

--EMPLOYEES OF IT_PROG OR ST_CLECK WHO ARE HAVING SALARY ABOVE 5000
SELECT FIRST_NAME,LAST_NAME,JOB_ID,SALARY FROM EMPLOYEES
WHERE (JOB_ID ='IT_PROG' OR JOB_ID = 'ST_CLERK') AND SALARY > 5000;



--EMPLOYEES OF IT_PROG OR ST_CLECK WHO ARE HAVING SALARY ABOVE 5000
--SYNTACTICALLY CORRECT BUT FUNCTIONALLY WRONG
SELECT FIRST_NAME,LAST_NAME,JOB_ID,SALARY FROM EMPLOYEES
WHERE JOB_ID ='IT_PROG' OR JOB_ID = 'ST_CLERK'AND SALARY > 5000;