--ORDER BY
--BY DEFAULT IT IS STORED IN ASCENDING ORDER IF WE DONT SPECIFY DESC OR ASC

--EMPLOYEES WHO RECIEVE SALARY MORE THAN 9000 SORTED FROM HIGHEST TO LOWEST SALARY
SELECT FIRST_NAME,LAST_NAME,SALARY FROM EMPLOYEES 
WHERE SALARY >9000 ORDER BY SALARY DESC;


--EMPLOYEES WHO RECIEVE SALARY MORE THAN 9000 SORTED FROM LOWEST TO HIGHEST SALARY
SELECT FIRST_NAME,LAST_NAME,SALARY FROM EMPLOYEES 
WHERE SALARY >9000 ORDER BY SALARY ASC;


--WE CAN ALSO SORT BY THE COLUMN NUMBER . I.E  SALARY IS THE 3RD COLUMN IN THE BELOW QUERY
--NOT RECOMMENDED AS CLOUMN ORDER MIGHT CHANGE.
SELECT FIRST_NAME,LAST_NAME,SALARY FROM EMPLOYEES 
WHERE SALARY >9000 ORDER BY 3 DESC;



--USING ALIASIS NAME TO SORT INSTEAD OF COLUMN NAME 
SELECT FIRST_NAME,LAST_NAME AS SURNAME,SALARY FROM EMPLOYEES 
WHERE SALARY >9000 ORDER BY SURNAME DESC;


--USING MULTIPLE COLUMNS SORTING IN THE SAME QUERY
SELECT FIRST_NAME,LAST_NAME AS SURNAME,SALARY FROM EMPLOYEES 
WHERE SALARY >9000 ORDER BY SALARY DESC,SURNAME DESC;