--ROW ID , ROW NUM

SELECT ROWNUM,ROWID,FIRST_NAME,SALARY FROM EMPLOYEES;

SELECT ROWNUM,ROWID,FIRST_NAME,SALARY FROM EMPLOYEES ORDER BY SALARY DESC;

--LIMIT THE OUTPUT TO ONLY 10 FIRST ROWS USING ROWNUM.
--TOP 10 HIGHEST SALARIED EMPLOYEES QUERY
SELECT FIRST_NAME,SALARY FROM EMPLOYEES 
WHERE SALARY > 10000 
  AND ROWNUM <= 10;
  
  
  --TOP 5 HIGHEST SALARIED EMPLOYEES FROM DEPARTMENT ID 80
  SELECT EMPLOYEE_ID,FIRST_NAME,LAST_NAME,SALARY,DEPARTMENT_ID,ROWNUM,ROWID FROM ( 
  SELECT EMPLOYEE_ID,FIRST_NAME,LAST_NAME,SALARY,DEPARTMENT_ID FROM EMPLOYEES
  WHERE department_id = 80
  ORDER BY SALARY DESC)
  WHERE ROWNUM <= 5;
  
  
  ------------------------------
  ----## WRONG QUERY ########
  -------THIS QUERY DOESNT GET THE TOP 5 HIGHEST PAID EMPLOYEES FROM 80 DEPARTMENT---
  SELECT EMPLOYEE_ID,FIRST_NAME,LAST_NAME,SALARY,department_id,ROWNUM,ROWID FROM EMPLOYEES
  WHERE department_id = 80
  AND   ROWNUM <= 5
  ORDER BY SALARY DESC; 
  
  
  
  
  
  
  
  
  