-------------SINGLE ROW SUB QUERIES------------------------------------

--EMPLOYEES HAVING MORE SALARY THAN JOHN

SELECT SALARY FROM EMPLOYEES
WHERE SALARY > (SELECT SALARY FROM EMPLOYEES
                WHERE EMPLOYEE_ID = 145);
                
                

--EMPLOYEES BELONGING TO SAME DEPARTMENT AS OF JHON AND EARNING LESS THAN JOHN

SELECT * FROM EMPLOYEES
WHERE DEPARTMENT_ID = 
                    (SELECT DEPARTMENT_ID FROM EMPLOYEES
                     WHERE EMPLOYEE_ID = 145)
AND SALARY < 
                    (SELECT SALARY FROM EMPLOYEES
                    WHERE EMPLOYEE_ID = 145);
                
            


			
--USING GROUP FUNCTION TO IDENTIFY WHO IS HIRED FIRST .

SELECT * FROM EMPLOYEES
WHERE HIRE_DATE = ( SELECT MIN(HIRE_DATE) FROM EMPLOYEES);



